### ISSUE TITLE
Only display Authors, not other types of Creators

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#12]
When importing to Zotero this item: https://link.springer.com/chapter/10.1007/978-94-007-5968-8_8
It imports 2 Authors and then 2 Editors.
The current behaviour of the plugin is to display the last Creator, so here the last Editor.
I only want to see the last Author in the Last Author column.

**Comment by mjthoraval** [comment]
Can I test the corrections, or do I need to wait for another pre-release?

**Comment by github-young** [comment]
Closed in PR #13.

**Attention**! Since the repo name was changed, please remove the previously installed plugin "Zotero Last Author", and install from the [latest release](https://github.com/github-young/zotero-better-authors/releases/latest), otherwise the updated may fail as described in #10.
