### ISSUE TITLE
Keep a separate Last Author column

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#15]
It is nice to have more functionalities in the new `Authors List` column.
But I still prefer keeping a separate column for the `Last Author`.
That column has a different purpose than the additional options, so I should not have to choose between one or the other.

**Comment by github-young** [comment]
I deleted that part in the last release as I thought it was not necessary to keep two columns. But as you suggested, I recovered it in [v3.1.1](https://github.com/github-young/zotero-better-authors/releases/tag/v3.1.1)
