### ISSUE TITLE
Structure the settings

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#17]
It is a bit confusing that the option to `Display first name as initials` is still visible even when I select the option to `Only display last name`. I would find it more intuitive to hide the first option if the second one is selected.
Maybe an exclusive choice between `Full first name` or `First name as initials` or `No first name` under the general category `First Name` would be more clear?

Some settings are relative to the formatting of a single author, while some settings are relative to the display of multiple authors.
Separating them in two different sections would probably be more clear.

If a separate Last Author column can be recovered, the options relative to that column should also be separated in another section.

**Comment by github-young** [comment]
Close in [v3.3.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.3.0)
