### ISSUE TITLE
Option not to show the last author

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#19]
At the moment, showing the first N authors will always keep the last author.
I would like to be able to recover the behaviour of the original `Creator` column, which shows `et al.` when there are 3 or more authors, but in that case only keep one author in front of the `et al.`.
With more flexibility, for example after how many authors it should trigger the `et al.`, and how many authors to keep in front of the `et al.`.

**Comment by github-young** [comment]
Close in [v3.3.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.3.0)
