### ISSUE TITLE
Other types of Creators to display

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#20]
I was probably a bit too fast on my [previous request](https://github.com/github-young/zotero-better-authors/issues/12) to limit the column of the plugin only to Authors.
There are actually some Item Types for which it makes sense to show other types of Creators:
- `Presentation` -> `Presenter`
- `Patent` -> `Inventor`
- `Video Recording` -> `Director`
- Maybe others?

So it would be nice to either make a hard list of what is considered to be an `Author`, or make it an option to choose which ones to display.

**Comment by github-young** [comment]
In my opinion, I would like to focus on authors (which are defined "author" in zotero item database) as this plugin is about authors not all the creators. But PRs are welcomed for such functions.

**Comment by mjthoraval** [comment]
For the Item Types I mentionned, they do not have any `Author`.
The first type of `Creator` they have, which I have listed, play the same role as an `Author`.
Otherwise, these Item Types will not have any `Author` to display.

**Comment by github-young** [comment]
I cannot spare time to realize this function but if you really need this, PRs are welcome.
