### ISSUE TITLE
Empty Last Author

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#22]
I have removed and reinstalled the plugin. But I still get an empty Last Author column.
The Report errors show:

```
1695554339589	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36


1695554341813	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]" {file: "chrome://zotero/content/xpcom/plugins.js" line: 307}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "uncaught exception: undefined"]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12


[JavaScript Error: "Component returned failure code: 0x8052000e (NS_ERROR_FILE_IS_LOCKED) [mozIStorageService.backupDatabaseFile]" {file: "chrome://zotero/content/xpcom/db.js" line: 1058}]

[JavaScript Error: "TypeError: emptyListMessage is null" {file: "chrome://zotero/content/standalone/standalone.js" line: 655}]
ZoteroStandalone</this.updateAddonsPane/<@chrome://zotero/content/standalone/standalone.js:655:7


appName => Zotero, version => 7.0.0-beta.40+24ae34104, os => Windows 10.0 19045, locale => en-GB, extensions => Zotero Better Authors (3.1.1, extension), Zotero PDF Preview (1.0.0-4, extension, disabled), Open PDF (0.0.1, extension, disabled), Zutilo Utility for Zotero (3.10.1a1, extension, disabled), Translate for Zotero (1.1.0-18, extension, disabled), Ethereal Style (3.1.2, extension, disabled), Better BibTex for Zotero (6.7.122, extension, disabled), Better Notes for Zotero (1.1.4-25, extension, disabled)
```

**Comment by mjthoraval** [comment]
The Better Authors settings do not seem to have any option to modify the parameters of the Last Author column?

![image](https://github.com/github-young/zotero-better-authors/assets/36054098/8a5c0e7a-9dae-44ae-912b-8d5a5ea72ea0)

**Comment by github-young** [comment]
Is this bug still existing? I cannot reproduce it on my Zotero.

The two columns share the same setting.

**Comment by mjthoraval** [comment]
Yes.
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/becb502d-6f24-4ff3-accd-767ee5f6bf02)

This line seems to be triggered by the plugin:
`[JavaScript Error: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.setIntPref]" {file: "chrome://zotero/content/xpcom/plugins.js" line: 307}]`

**Comment by github-young** [comment]
I have tried with a new computer and a newly downloaded Zotero 7 Beta but I cannot reproduce it. It displays both columns correctly.

Can you test with a new Zotero profile (see [here](https://www.zotero.org/support/kb/multiple_profiles) for instructions) and see if it works well? This action will not break your literature data.

If the above method works, then maybe it is due to some unknown reasons (like cache or residuals, but it does not make sense because it works on both old and new computers in my side). If the new profile works I suggest you just migrate to the new profile.

**Comment by mjthoraval** [comment]
I have made a new Zotero profile. But I still get the same problem.
Installing on a new computer works fine indeed.
So I don't understand what is broken here...

**Comment by github-young** [comment]
> I have made a new Zotero profile. But I still get the same problem. Installing on a new computer works fine indeed. So I don't understand what is broken here...

If so I think it is not related with profile but database. I don't either know how to deal with such cases.

But, just want to make sure, how did you remove and install the plugin? Did you restart Zotero after removing the plugin, and then install the plugin, and restart Zotero again? Could you try it this can help?

**Comment by mjthoraval** [comment]
`Tools` -> `Add-ons` -> 3 dots on the right side of the plugin -> `Remove`
Restart Zotero
`Tools` -> `Add-ons` -> Wheel on the top right, next to `Manage Your Extensions` -> `Install Add-on From File` -> Select the .xpi file of the plugin
Restart Zotero

--> Still the same problem.

I have also tried to Check Database Integrity (no error found).
I have also tried to remove the plugin -> install Zotero 6.0.27 -> and then reinstall again Zotero 7.0.0-beta.40. 
--> Still the same problem.

**Comment by mjthoraval** [comment]
> The two columns share the same setting.

Will each column get their own settings eventually?

**Comment by github-young** [comment]
> > The two columns share the same setting.
> 
> Will each column get their own settings eventually?

I am working on it.

**Comment by mjthoraval** [comment]
I have completely deleted Zotero from my computer and installed it again, downloading my data from the Zotero online storage.
The problem is now fixed. I don't know what happened.
Thanks.
