### ISSUE TITLE
Add previews

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#24]
It takes quite some time to test different options, as you need to close and restart Zotero every time to see the result.
It would be very useful to have a Preview tool to show what the results will look like in each column. This would make the tunning of parameters much faster.

A similar functionality is used for example in the `Settings` -> `General` -> `File Renaming` -> `Customize Filename Format...` -> `Preview`.

**Comment by github-young** [comment]
Thanks to @jstzwj , [v4.0.0](https://github.com/github-young/zotero-better-authors/releases/tag/v4.0.0) now supports previews. Please close this issue if it is solved.

**Comment by mjthoraval** [comment]
Thank you very much!
Closed.
