### ISSUE TITLE
Display first name options as drop-down menu

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#25]
Thank you very much for all the improvements!

In the latest release [v3.3.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.3.0), the style setting for the first name is a bit confusing: you can tick `initials` and `none` together, even though if you select `none`, the `initials` tick does not have any effect.

It may be better to put them in a drop-down menu?
`Display first name as`:
- `Full`
- `Initials`
- `No`

I had mentioned this in a [previous issue](https://github.com/github-young/zotero-better-authors/issues/17), but I separate it here for clarity.

**Comment by github-young** [comment]
the thing is I don't know how to implement the "disable" function, so I mark this with a `help wanted` label. Same reason for #24

**Comment by github-young** [comment]
but honestly I think it does not affect the use: if you tick both "initials" and "none", and it is reasonable that "none" overwrites "initials". let's wait for helpers :)

**Comment by mjthoraval** [comment]
Thank you for your reply.
The plugin is already functional and extremelly helpful as it is now.
I just put some comments and ideas to keep track of them if anyone can implement them.
But this is not a complain about the amazing work done already.
Thanks again!

**Comment by github-young** [comment]
closed in [v3.4.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.4.0)
