### ISSUE TITLE
Last author indicator and sorting scheme

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#26]
I see in [v3.3.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.3.0) that a `1` has been added in front of the first author if it is the only author. 

Could you clarify what is its intended use case?

I am not sure how to use it.
At the moment, it breaks the sorting of the `Authors List` column.
Could you add an option to hide it?

**Comment by github-young** [comment]
> I see in [v3.3.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.3.0) that a `1` has been added in front of the first author if it is the only author.
> 
> Could you clarify what is its intended use case?
> 
> I am not sure how to use it. At the moment, it breaks the sorting of the `Authors List` column. Could you add an option to hide it?

Oh I intentionally added it. Is it affecting the "Last Author" column? I can remove it (and the `*` after it) for only one author case in next commit

**Comment by github-young** [comment]
closed in [v3.4.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.4.0)

**Comment by mjthoraval** [comment]
Thank you for removing the 1. It was just that I did not know how to use it. But I guess there could be some useful ways to use that. Maybe an option to put the number of authors in front of the `Authors List` (not only for a single author), so that people could sort by the number of authors?


> Is it affecting the "Last Author" column?

No.


> If there is no "1" in front, will the sorting still be affected by the "*"?

The sorting will always be affected by the `*`, not only the first author.
See for example:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/f7ea909f-3d27-4618-ad74-190bef527209)


> I can remove it (and the `*` after it) for only one author case in next commit

I feel that removing the `*` on the last author only when there is a single author is a bit arbitrary.
But I do not have a strong feeling about it, as I could understand that people may prefer this.
As seen in the previous point, the sorting argument is not limited to the first author, so it cannot justify alone this choice.

On the sorting problem, I understand that it is possible to use a sort order different from what is displayed in the column. For example, the `Creator` column displays `et al.` while still using the full authors list for sorting.
So I understand that it would be possible technically to ignore the last author indicator in the sorting logic, which would allow you to keep the `*` on all last authors without affecting the sorting order.

**Comment by github-young** [comment]
> The sorting will always be affected by the *, not only the first author.

This is quite annoying, I didn't realize it. I am thinking if it is good to move the indicator to the end of the names? Like: `Last Author*`? Or add a choice about this.

> So I understand that it would be possible technically to ignore the last author indicator in the sorting logic

True, but probably that involves the Zotero API operations, maybe I need to learn more about it. 

I will reopen this issue, but change the title a little bit

**Comment by mjthoraval** [comment]
> I am thinking if it is good to move the indicator to the end of the names? Like: Last Author*? Or add a choice about this.

I guess that any addition of a character will affect the sorting, with probably more or less impact, but also in a more or less suitable way visually.

But indeed, some more flexibility on the formatting options on this would be welcome, independently of the longer term fix (option to ignore these characters in the sorting).

**Comment by github-young** [comment]
> I guess that any addition of a character will affect the sorting, with probably more or less impact, but also in a more or less suitable way visually.

Yes. After a second look at the screenshot you posted about the sorting issue, I think it is still within the logic, because if the author list is inserted by any character, the sorting order will be affected by the inserted character, no matter it is a letter or a symbol like `*`. 

So I guess it is better to add a note by the `indicator` setting explaining about this issue and let the users decide whether to use an extra symbol or not (if not, they can just delete the content in the box).

As for the sorting with original authors instead of the displayed authors, after searching in docs and for plugins, I think it is related with the source code of Zotero which is way beyond my programming ability, so let's hope any helpers could help on this.

**Comment by mjthoraval** [comment]
It may be good to ask this question on the [zotero-dev forum](https://groups.google.com/g/zotero-dev).

**Comment by mjthoraval** [comment]
Another solution would be to put some kind of formatting directly on the last author (bold, text colour or background colour) which would not affect the text itself.
But I guess this is not possible in the center pane of Zotero?

**Comment by github-young** [comment]
closed in [v3.5.1](https://github.com/github-young/zotero-better-authors/releases/tag/v3.5.1)

I added an option to change the position of the indicator symbol.
