### ISSUE TITLE
Last author symbol ignored when show all authors

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#32]
If you untick the Last author, the Last author symbol is ignored:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/df0e2962-61a2-4027-8235-3ca600b579de)

If I tick the Last author, I get back to [the other issue](https://github.com/github-young/zotero-better-authors/issues/31).
So something probably needs to be fixed here.

**Comment by github-young** [comment]
Here "all" means all the first authors (excluding the last author since you untick it). So it is not unexpected.

I am checking the other issue #31

**Comment by mjthoraval** [comment]
I find the current implementation of "all authors" quite confusing:
- In my view, putting `0` in the field `First author(s)   Display first 0 authors` should simply mean 0 first authors. So the same as unticking that line. Since it is already covered by unticking, you can indeed decide to assign it to another meaning, but I find this confusing.
- So you mean that `0 means all` means `0 means all first authors excluding the last author`? I also find this confusing.

The current implementation could probably work, so nothing critical here, but it could probably be improved.
What about the structure proposed in this other issue https://github.com/github-young/zotero-better-authors/issues/33?

**Comment by github-young** [comment]
> In my view, putting `0` in the field `First author(s)   Display first 0 authors` should simply mean 0 first authors. So the same as unticking that line.

No, it is not. If you want to display 0 first authors, that is, not to display first authors, you just untick the checkbox.
Putting 0 here is just to make a choice for the "all first authors" case. I have added the "0 means all" explanation after it and I think it is easy to understand the scope of "all" here because the last author is controlled by the checkbox below.


>     * So you mean that `0 means all` means `0 means all first authors excluding the last author`?

Yes. If you find it confusing, I can put your sentence `0 means all first authors excluding the last author` in the description.
 
> The current implementation could probably work, so nothing critical here, but it could probably be improved. What about the structure proposed in this other issue #33?

I have replied in #33. PRs are welcome.

**Comment by mjthoraval** [comment]
> If you find it confusing, I can put your sentence `0 means all first authors excluding the last author` in the description.

Thank you for the clarification.
I guess replacing `First author(s)` with `First author(s) (excluding the Last author)` would help clarify the defintiion of how the settings here are applied. Is that correct?

I will spend some time playing with the parameters with this understanding and see if that works.

Thank you very much!

**Comment by github-young** [comment]
OK I will put this note in the settings
