### ISSUE TITLE
[Feature request] Text formatting on the authors displayed

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#35]
It is already possible to add [rich text formatting in the titles](https://www.zotero.org/support/kb/rich_text_bibliography).
I would like to do the same for the authors columns provided by this plugin.
Is it already technically possible from the plugins interface? Or is it something that I need to ask Zotero? Or should it be asked in the devs discussion channel?

Examples of use case:
- Put the last name in bold in the Authors List
- Put the Last Author identifier as superscript

Eventually, more advanced formatting options would be nice also, like highlighting with a color, change color font, background color of the whole field,, underline, ...

**Comment by northword** [comment]
in chinese: 如果你希望在参考文献表中对作者列表应用粗体、上标等样式，应该在 csl 中完成，而不是在 zotero 中修改字段数据。

另外，更改颜色、突出显示等无法实现，我比较好奇这一样式的作用--据我所知，没有任何引文格式需要将作者列表显示为不同的颜色。

**Comment by github-young** [comment]
It is for `bibliographic output` as noted in the link you provided. I don't see any posts that can change the format _in situ_.

**Comment by mjthoraval** [comment]
Maybe an illustration will work better here:
![image](https://github.com/github-young/zotero-better-authors/assets/36054098/f8d80f18-6d14-44bd-bbd4-4fc83be8c688)

**Comment by github-young** [comment]
You can find that these HTML tags only apply to the `title` field while other fields are not response to them.

**Comment by mjthoraval** [comment]
Yes, from a user's perspective, other fields do not render HTML tags.

The current functionality already implemented in Zotero for the `Title` has several aspects:
1. You can modify the actual metadata content to include more complex formatting.
2. These modifications will displayed accordingly in the center pane.
3. The formatting will be carried to different export formats of the item.

Using all these 3 functionalities on the `Creator` field does not make any sense, because the author of an article will never carry any formatting. The formatting is done later by the citation tool you will use.

Here, I am just asking for point 2, which is changing the displayed information in the center pane, which is what this plugin is doing. Since it is possible to do it for the `Title` field, I do not see any reason why it would not be possible technically to do it also the new columns produced by your plugin.

> Is it already technically possible from the plugins interface? Or is it something that I need to ask Zotero? Or should it be asked in the devs discussion channel?

Now the questions is: Considering that it is technically possible to do it in Zotero, is this feature available from the API tools? I guess is it just a rendering step done on the `Title` field that should work as well for any content you put in it?
- If yes: Then it would be nice to get more formatting options in the plugin, as mentionned in my first post.
- If no: Is it possible to ask Zotero in the zotero-dev channel if they could add this functionality for developpers?

As I have explained above, it does not make any sense to make this request in the Zotero Forums, as this should not be implemented to modify the `Creators` field directly in the metadata. So, the appropriate place to ask would be the zotero-dev channel. If the feature is not already available in the API, it would be better that this question comes from a developper to ask the question properly.

**Comment by github-young** [comment]
Then do it yourself.
