### ISSUE TITLE
博士论文issue

### ISSUE THREAD

**Issue by pencilheart** [github-young/zotero-better-authors#39]
对于博士论文，导师有时为contributor，但由于不是author此插件无法显示为最后一个作者。

**Comment by github-young** [comment]
Can you provide an example for me to check this issue?

**Comment by pencilheart** [comment]
以下是网站链接：
https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CDFD&dbname=CDFDLAST2019&filename=1019832218.nh&uniplatform=NZKPT&v=jlql-Idx0b7JRDfkFnvgkqLFa8WLtd1lLPUgHxj9vAHSpIgMjsjq3aqvsEMoxZ6F

以下是条目信息：
[Exported Items.bib.zip](https://github.com/github-young/zotero-better-authors/files/13787950/Exported.Items.bib.zip)

**Comment by github-young** [comment]
Thanks for your issue. I am thinking if a thesis should have a "author list"? In principle, a thesis is completed by one student only, otherwise it is violating the academic regulations.

And the second reason is elaborated in #40 . Thanks for your understanding.
