### ISSUE TITLE
Support Patent's inventor

### ISSUE THREAD

**Issue by northword** [github-young/zotero-better-authors#40]
Thinks your work! 

There is a feature request: support patent's inventor.

![image](https://github.com/github-young/zotero-better-authors/assets/44738481/b5c2232d-fabe-4b0c-93ab-9ff8339cd5d9)

**Comment by github-young** [comment]
Thanks for your issue. After looking into the patent item in Zotero, I found two points that may cause trouble for me:

1. Zotero stores the creators with various types, including `author` for articles, `inventor` for patents, and even `director` for movies. As this project mainly focuses on journal articles, I think it may be a little bit time-consuming for me to cover all the types --- once I support patents, I have to support all the other types.
2. Another reason is that an author list in the patent does not reveal any order information, for some patents I searched, the PI is placed in the first position, so it could be quite confusing when processing both articles and patents in this plugin.

Therefore I am sorry that I cannot offer help on this.
