### ISSUE TITLE
能不能适配一个Zotero 6版本的

### ISSUE THREAD

**Issue by bigben446** [github-young/zotero-better-authors#46]

**Comment by github-young** [comment]
Sorry it was designed for Zotero 7 from the very beginning.

The development of add-ons for Zotero 6 is completely different from that of Zotero 7, so I cannot achieve that.

**Comment by github-young** [comment]
BTW, Zotero 6 has been announced to be out-dated and will not get official support in the future. We strongly recommend you switch to Zotero 7.
