### ISSUE TITLE
how to install this plugin in zotero?

### ISSUE THREAD

**Issue by Jiale-6** [github-young/zotero-better-authors#55]
This plugin seems good for me! But i can not install it. I have tried to put it into "add-on manager" in zotero 7.00 beta, but it does not work. How can i solve this? Thank you!

**Comment by github-young** [comment]
Can you provide more details, including:
- Where did you download the plugin file?
- What is the version of the downloaded plugin file?
- What is the detailed version of Zotero?
- Any screenshots to show it is not working?

**Comment by Jiale-6** [comment]
I have found where is my wrong, i just download the .zip file, which does not work.
When i try .xpi file in https://github.com/github-young/zotero-better-authors/releases/tag/v4.1.3, i find it work!
I'm not very familiar with this software and github. Thanks again !!!

**Comment by POBrien333** [comment]
I've just come across this issue as I had the same question.
The "Releases" link on the right is very easy to miss. Could you add a heading in your Readme.md called "Installation" to explain and link to how to do that?

**Comment by github-young** [comment]
> I've just come across this issue as I had the same question. The "Releases" link on the right is very easy to miss. Could you add a heading in your Readme.md called "Installation" to explain and link to how to do that?

Thanks. Just updated the readme

**Comment by POBrien333** [comment]
Great. thank you so much. I'm including your plugin in a blog, so that's really appreciated to help future users. ;)
