### ISSUE TITLE
Reformat the Creator column

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-better-authors#6]
This probably goes beyond the scope of this plugin, but I still wanted to mention it here, as similar tools would probably need to be used.

Some of the options would be:
- Choose the authors to display: first N authors and eventually add the last author
- Choose how to display the authors (only last name, last name followed by first name or the opposite order, keep only initials of the first name, ...)

Some previous plugins have made some steps in this direction:
- [Full Creator](https://github.com/normanleiden/zotero-plugin-full-creator) (and this [forked version](https://github.com/pencilheart/zotero-plugin-full-creator_lastname-firstname) or the previous versions for Zotero 5, like [this one](https://github.com/liwind/zotero-fullcreator) or [that one](https://github.com/normanfoster/zotero-fullcreator)). But they have not been updated for Zotero 7.
- It was mentioned in [this post](https://forums.zotero.org/discussion/90736/change-number-of-authors-in-creator-column#latest) that the plugin [Ethereal Style](https://github.com/MuiseDestiny/zotero-style) can also do that, but the plugin is too heavy and crashes my Zotero. I would just need the formatting of the creator column from that plugin. So it may be worth merging these functionalities here if they are not too complicated.

Am I missing another plugin doing that in Zotero 7?
There is an issue opened in the Zotero GitHub on this: https://github.com/zotero/zotero/issues/2831

**Comment by github-young** [comment]
I see, but manipulating the `` creators `` filed is out of the scope of this plugin which focuses on **last** author.

Probably I could have a try to develop a new plugin with such functions when I get more familiar with TypeScript and Zotero plugin development, but in short future I am afraid I cannot achieve this due to limited programming experiences and time.

**Comment by mjthoraval** [comment]
To clarify, the idea is just to create another column similar to the `Creator` column, not to modify it.
This is what the plugins I mentioned did.
But, indeed, it may fit better in a new plugin.
Thanks!

**Comment by github-young** [comment]
Thanks to @jstzwj , closed in [v3.0.0](https://github.com/github-young/zotero-better-authors/releases/tag/v3.0.0)

And I changed the plugin name to "Zotero Better Authors" because the functions are not limited in displaying "last" author but the customizable author list.
